/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 billboard_3d.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/billboard_3d.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="3d_plane" geometry={nodes['3d_plane'].geometry} material={materials['3d_plane']} position={[-0.118, 0.199, -0.02]} rotation={[0, -0.062, -1.595]} />
        <mesh name="vid_plane" geometry={nodes.vid_plane.geometry} material={materials.vid_plane} position={[1.715, 0.438, -0.156]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={[2.98, 1, 1.68]} />
      </group>
    </group>
  )
}

useGLTF.preload('/billboard_3d.glb')
